// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID           int32
	EventTypeID  int32
	UserID       int32
	UserPeopleID pgtype.Int4
	Details      []byte
	OccurredAt   pgtype.Timestamptz
}

type EventType struct {
	ID   int32
	Name string
	Icon string
}

type Habit struct {
	ID            int32
	TypeID        int32
	UserID        int32
	Name          string
	Frequency     pgtype.Int4
	FrequencyType pgtype.Text
	Color         string
	Icon          string
	MinFrequency  pgtype.Int4
	NotifyAt      interface{}
}

type HabitTrack struct {
	ID      int32
	HabitID int32
	DoneAt  pgtype.Timestamptz
	IsValid pgtype.Bool
	Details []byte
}

type HabitType struct {
	ID   int32
	Type string
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserBook struct {
	ID          int32
	UserID      int32
	Name        string
	CurrentPage int32
	Pages       int32
	Finished    bool
}

type UserPerson struct {
	ID       int32
	UserID   int32
	Name     string
	Relation pgtype.Text
}
